sources:
  - Anvers.glyphspackage
axisOrder:
  - wght
familyName: Anvers
stat:
  Anvers[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Semibold
      value: 550
    - name: Bold
      value: 700